# Generated by Django 6.1.1 on 2026-09-19 10:51

import apps.core_common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('question_count_choices', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'abstract': False,
            },
            bases=(apps.core_common.models.SluggedModel, models.Model),
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_tags', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='categories.category')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rooms.room')),
            ],
            options={
                'verbose_name_plural': 'room categories',
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('room', 'category'), name='unique_room_category')],
            },
        ),
    ]
