# Generated by Django 6.1.1 on 2026-09-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
