# Generated by Django 6.1.1 on 2026-09-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_player_is_bot_player_players_pla_is_bot_f8570c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=50)),
                ('question_id', models.CharField(max_length=64)),
                ('times_seen', models.PositiveSmallIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_exposures', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['times_seen'], name='exposure_qu_times_s_204ebf_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'question_type', 'question_id'), name='uniq_player_question_exposure')],
            },
        ),
    ]
