# Generated by Django 6.1.1 on 2026-09-10 07:59

import apps.players.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('display_name', models.CharField(max_length=30)),
                ('has_auto_name', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.players.models.avatar_upload_to)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['display_name'], name='players_pla_display_584b62_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_player_display_name')],
            },
        ),
    ]
