# Generated by Django 6.1.1 on 2026-09-10 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_bot'], name='players_pla_is_bot_f8570c_idx'),
        ),
    ]
