# Generated by Django 6.1.1 on 2026-09-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_is_bot_player_players_pla_is_bot_f8570c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mascot',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
