# Generated by Django 6.1.1 on 2026-09-09 23:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnsRowsQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('row_count', models.PositiveSmallIntegerField()),
                ('column_count', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeTextQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrixColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='questions.columnsrowsquestion')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='questions.columnsrowsquestion')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='questions.columnsrowsquestion')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='questions.matrixcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='questions.matrixrow')),
            ],
            options={
                'ordering': ('row__order', 'column__order'),
            },
        ),
        migrations.CreateModel(
            name='MultipleAnswerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.multipleanswerquestion')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('instruction', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct_position', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.orderingquestion')),
            ],
            options={
                'ordering': ('correct_position',),
            },
        ),
        migrations.CreateModel(
            name='SingleAnswerImageQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='questions/answers/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.singleanswerimagequestion')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleAnswerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.singleanswerquestion')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('answer', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeTextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='questions.freetextquestion')),
            ],
            options={
                'ordering': ('value',),
                'constraints': [models.UniqueConstraint(fields=('question', 'value'), name='uniq_free_text_answer_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='matrixcolumn',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_matrix_column_order'),
        ),
        migrations.AddConstraint(
            model_name='matrixrow',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_matrix_row_order'),
        ),
        migrations.AddConstraint(
            model_name='matrixcell',
            constraint=models.UniqueConstraint(fields=('row', 'column'), name='uniq_matrix_cell_per_intersection'),
        ),
        migrations.AddConstraint(
            model_name='multipleansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_multiple_answer_option_order'),
        ),
        migrations.AddConstraint(
            model_name='orderingoption',
            constraint=models.UniqueConstraint(fields=('question', 'correct_position'), name='uniq_ordering_option_position'),
        ),
        migrations.AddConstraint(
            model_name='imageansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_image_answer_option_order'),
        ),
        migrations.AddConstraint(
            model_name='singleansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_single_answer_option_order'),
        ),
    ]
