# Generated by Django 6.1.1 on 2026-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnsrowsquestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freetextquestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multipleanswerquestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderingquestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singleanswerimagequestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singleanswerquestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truefalsequestion',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
