# Generated by Django 6.1.1 on 2026-09-18 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('questions', '0004_columnsrowsquestion_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradualHintsQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hint_interval_seconds', models.PositiveSmallIntegerField(default=5, help_text='Seconds between one hint being revealed and the next.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradualHintsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=60)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_fields', to='questions.gradualhintsquestion')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GradualHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='questions.gradualhintsquestion')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GradualHintsFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='questions.gradualhintsfield')),
            ],
            options={
                'ordering': ('value',),
                'constraints': [models.UniqueConstraint(fields=('field', 'value'), name='uniq_gradual_hints_field_answer')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradualhintsfield',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_gradual_hints_field_order'),
        ),
        migrations.AddConstraint(
            model_name='gradualhint',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_gradual_hint_order'),
        ),
    ]
