# Generated by Django 6.1.1 on 2026-09-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_gradualhintsquestion_gradualhintsfield_gradualhint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradualhintsfield',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number')], default='text', max_length=16),
        ),
    ]
