# Generated by Django 6.1.1 on 2026-09-18 14:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('questions', '0006_gradualhintsfield_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameAsManyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveSmallIntegerField(help_text='Difficulty, 1 (easiest) to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('is_active', models.BooleanField(default=True)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dataset', models.CharField(choices=[('nba-career-stats', 'NBA career totals (baked artifact)')], default='nba-career-stats', help_text='Which baked artifact the qualifying players come from.', max_length=32)),
                ('stat', models.CharField(help_text="The artifact column this question draws its line through, e.g. 'fg3m'.", max_length=60)),
                ('comparison', models.CharField(choices=[('at-least', 'At least'), ('at-most', 'At most')], default='at-least', max_length=16)),
                ('threshold', models.FloatField(help_text="The figure a player's stat is compared against.")),
                ('target_score', models.PositiveSmallIntegerField(help_text="Popularity points worth full credit. A name pays the player's 2..10 fame grade, so an obvious pick is worth 2 and a deep cut 10.", validators=[django.core.validators.MinValueValidator(5)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='categories.category')),
            ],
            options={
                'ordering': ('slug',),
                'abstract': False,
            },
        ),
    ]
