# Generated by Django 6.1.1 on 2026-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_nameasmanyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnsrowsquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='freetextquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='gradualhintsquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='multipleanswerquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='nameasmanyquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='orderingquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='singleanswerimagequestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='singleanswerquestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='truefalsequestion',
            name='pre_question_info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
