# Generated by Django 6.1.1 on 2026-09-10 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('played', 'Played to completion'), ('abandoned', 'A player left mid-match')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchups', to='categories.category')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchupPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_answer_time_ms', models.PositiveBigIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.matchup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchups', to='players.player')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchupQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=64)),
                ('question_type', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='matches.matchup')),
            ],
            options={
                'ordering': ('matchup', 'order'),
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('score', models.FloatField()),
                ('points', models.PositiveIntegerField()),
                ('response_time_ms', models.PositiveBigIntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('matchup_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='matches.matchupquestion')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='matches_matchup_completed_has_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='matchupplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('matchup', 'player'), name='uniq_matchup_player'),
        ),
        migrations.AddConstraint(
            model_name='matchupquestion',
            constraint=models.UniqueConstraint(fields=('matchup', 'order'), name='uniq_matchup_question_order'),
        ),
        migrations.AddConstraint(
            model_name='matchupquestion',
            constraint=models.UniqueConstraint(fields=('matchup', 'question_type', 'question_id'), name='uniq_matchup_question_ref'),
        ),
        migrations.AddConstraint(
            model_name='playeranswer',
            constraint=models.UniqueConstraint(fields=('matchup_question', 'player'), name='uniq_player_answer_per_question'),
        ),
    ]
