# Generated by Django 6.1.1 on 2026-09-10 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0002_player_is_bot_player_players_pla_is_bot_f8570c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('accuracy', models.FloatField()),
                ('min_response_fraction', models.FloatField()),
                ('max_response_fraction', models.FloatField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to='players.player')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('accuracy__gte', 0.0), ('accuracy__lte', 1.0)), name='bot_profile_accuracy_in_range'),
                    models.CheckConstraint(condition=models.Q(('min_response_fraction__gte', 0.0), ('max_response_fraction__lte', 1.0)), name='bot_profile_response_fraction_in_range'),
                    models.CheckConstraint(condition=models.Q(('max_response_fraction__gte', models.F('min_response_fraction'))), name='bot_profile_response_band_ordered'),
                ],
            },
        ),
    ]
