# Generated by Django 6.1.1 on 2026-09-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_botprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='is_ranked',
            field=models.BooleanField(default=True),
        ),
    ]
