# Generated by Django 6.1.1 on 2026-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchup_is_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupquestion',
            name='is_tiebreaker',
            field=models.BooleanField(default=False),
        ),
    ]
