# Generated by Django 6.1.1 on 2026-09-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchupquestion_is_tiebreaker'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchups', to='rooms.room'),
        ),
    ]
